/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Napakalaki.Player;
import Napakalaki.Treasure;
import java.awt.Component;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author antonio
 */
public class PlayerView extends javax.swing.JPanel {
    Player playerModel;
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
        FlowLayout LayoutPrueba = new FlowLayout();
        LayoutPrueba.setAlignment(FlowLayout.TRAILING);
        TesorosOcultos.setLayout(LayoutPrueba);
        TesorosVisibles.setLayout(LayoutPrueba);
    }
    public void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
            // Se elimina la información antigua
            aPanel.removeAll();
            // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
            // al panel
            for (Treasure t : aList) {
                TreasureView aTreasureView = new TreasureView();
                aTreasureView.setTreasure (t);
                aTreasureView.setVisible (true);
                aPanel.add (aTreasureView);
            }
// Se fuerza la actualización visual del panel
            aPanel.repaint();
            aPanel.revalidate();
    }
    
    public void setPlayer(Player p){
        playerModel=p;
        Nombrejug.setText((playerModel.getName()));
        NivelJu.setText(Integer.toString(playerModel.getLevels()));
        fillTreasurePanel (TesorosVisibles, playerModel.getVisibleTreasures());
        fillTreasurePanel (TesorosOcultos, playerModel.getHiddenTreasures());
        repaint();
        revalidate();
              
    }
    public JPanel getHiddenTreasure() {
        return TesorosOcultos;
    }
    public JPanel getVisiblesTreasure(){
        return TesorosVisibles;
    }
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
// Se recorren los tesoros que contiene el panel,
// almacenando en un vector aquellos que están seleccionados.
// Finalmente se devuelve dicho vector.
            TreasureView tv;
            ArrayList<Treasure> output = new ArrayList();
            for (Component c : aPanel.getComponents()) {
                    tv = (TreasureView) c;
                    if ( tv.isSelected())
                        output.add ( tv.getTreasure());
            }
            return output;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TesorosOcultos = new javax.swing.JPanel();
        jtreasureHidden = new GUI.TreasureView();
        TesorosVisibles = new javax.swing.JPanel();
        jtreasureVisible = new GUI.TreasureView();
        Nombrejug = new javax.swing.JLabel();
        NivelJu = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(248, 254, 1))); // NOI18N

        TesorosOcultos.setBackground(new java.awt.Color(63, 22, 149));
        TesorosOcultos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tesoros Ocultos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(248, 254, 1))); // NOI18N

        jtreasureHidden.setBackground(new java.awt.Color(38, 124, 184));
        jtreasureHidden.setBorder(null);
        jtreasureHidden.setPreferredSize(new java.awt.Dimension(117, 193));
        TesorosOcultos.add(jtreasureHidden);

        TesorosVisibles.setBackground(new java.awt.Color(63, 22, 149));
        TesorosVisibles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tesoros Visibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(248, 254, 1)))); // NOI18N

        jtreasureVisible.setBackground(new java.awt.Color(38, 124, 184));
        jtreasureVisible.setPreferredSize(new java.awt.Dimension(117, 193));
        TesorosVisibles.add(jtreasureVisible);

        Nombrejug.setBackground(new java.awt.Color(103, 205, 212));
        Nombrejug.setForeground(new java.awt.Color(254, 254, 254));
        Nombrejug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombrejug.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(248, 254, 1)))); // NOI18N

        NivelJu.setBackground(new java.awt.Color(103, 204, 212));
        NivelJu.setForeground(new java.awt.Color(254, 254, 254));
        NivelJu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NivelJu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nivel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(248, 254, 1)))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TesorosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(Nombrejug, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NivelJu, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TesorosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombrejug, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(NivelJu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TesorosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TesorosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NivelJu;
    private javax.swing.JLabel Nombrejug;
    private javax.swing.JPanel TesorosOcultos;
    private javax.swing.JPanel TesorosVisibles;
    private GUI.TreasureView jtreasureHidden;
    private GUI.TreasureView jtreasureVisible;
    // End of variables declaration//GEN-END:variables
}
