/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.Treasure;

/**
 *
 * @author antonio
 */
public class TreasureView extends javax.swing.JPanel {

     Treasure  treasureModel;
     private boolean selected=false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    public void setTreasure(Treasure t){
        treasureModel=t;
        
        JTreasure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Tesoros/"+treasureModel.getName()+".jpg")));
        repaint();
    }
    
    public boolean isSelected(){
        return selected;
    }
    public Treasure getTreasure(){
        return treasureModel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTreasure = new javax.swing.JLabel();

        JTreasure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JTreasure.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTreasure.setMaximumSize(new java.awt.Dimension(117, 119));
        JTreasure.setPreferredSize(new java.awt.Dimension(117, 119));
        JTreasure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreasureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTreasure, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTreasureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreasureMouseClicked
        // TODO add your handling code here:
        if (this.isSelected()){
            this.selected=false;
            JTreasure.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        }else{
            JTreasure.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 140, 0)));
            this.selected=true;
        }
        repaint();
    }//GEN-LAST:event_JTreasureMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTreasure;
    // End of variables declaration//GEN-END:variables
}
